###课程内容分页条件查询
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java"
}

###查询课程分类
GET {{content_host}}/content/course-category/tree-nodes


###新增课程
POST {{content_host}}/content/course

### 测试jwt
GET http://localhost:5200/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODY0NzM5OTMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImE1YjdlZTE5LTU2OTItNDdkOC1hZWFiLTYxNzI2NGY2NTNiNiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.Q8vUllA6HU_h5qchwuOfZrjPUV2pveRUGU1a5TFFP9g

### 测试网关
GET http://localhost:5200/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLjUxeHVlY2hlbmcuY24vZGRkZlwiLFwidXR5cGVcIjpcIjEwMTAwMVwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODY0OTM0MDAsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiZTdlZGUwMTYtODJjMi00OTAyLWI3Y2MtZjhhZDIwOGY2M2MzIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.ckl95DfRBFXzzMb7Luwd8x6xG4vb2jaoyJNv0XM1DIA
